name: Reaction
options:
  deploymentTarget:
    iOS: 14.0
  # postGenCommand: bundle exec pod install

packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.4.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.19.0
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: 10.14.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.6
schemes:
  Local:
    build:
      targets:
        ReactionLocal: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: ReactionTests
          parallelizable: true
          randomExecutionOrder: true
  Staging:
    build:
      targets:
        ReactionStaging: all
    run:
      config: Debug
  Production:
    build:
      targets:
        ReactionProduction: all
    run:
      config: Debug

targets:
  ReactionLocal:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Reaction
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.chemist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.3.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Local
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Rswift
        product: RswiftLibrary
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseMessaging
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
    postBuildScripts:
      - script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
        name: Run Firebase Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  ReactionStaging:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Reaction
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ReactionStaging.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.chemist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.3.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Staging
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Rswift
        product: RswiftLibrary
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseMessaging
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
    postBuildScripts:
      - script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
        name: Run Firebase Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  ReactionProduction:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: reaction
    dependencies:
      - package: Rswift
        product: RswiftLibrary
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Reaction/Generated/R.generated.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ReactionProduction.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.example.junpei.chemi
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.3.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~7266182338
          ADMOB_UNIT_ID: ca-app-pub-5587141252700968/3350341396
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~7266182338
          ADMOB_UNIT_ID: ca-app-pub-5587141252700968/3350341396
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Rswift
        product: RswiftLibrary
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseMessaging
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
    postBuildScripts:
      - script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
        name: Run Firebase Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  ReactionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ReactionTests
    settings:
      base:
        INFOPLIST_FILE: ReactionTests/Info.plist
    dependencies:
      - target: ReactionLocal
  ReactionUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ReactionUITests
    settings:
      base:
        INFOPLIST_FILE: ReactionUITests/Info.plist
    dependencies:
      - target: ReactionLocal
