name: Reaction
options:
  deploymentTarget:
    iOS: 14.0
  postGenCommand: bundle exec pod install

packages:
  R.swift.Library:
    url: https://github.com/mac-cain13/R.swift.Library
    from: 5.4.0

schemes:
  Local:
    build:
      targets:
        ReactionLocal: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: ReactionTests
          parallelizable: true
          randomExecutionOrder: true
  Staging:
    build:
      targets:
        ReactionStaging: all
    run:
      config: Debug
  Production:
    build:
      targets:
        ReactionProduction: all
    run:
      config: Debug

targets:
  ReactionLocal:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: reaction
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.chemist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.2.3
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Local
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Reaction/Generated/R.generated.swift
  ReactionStaging:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: reaction
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.chemist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.2.3
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Staging
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Reaction/Generated/R.generated.swift
  ReactionProduction:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: reaction
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Reaction/Generated/R.generated.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.junpei.chemi
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: Reaction/Info.plist
        MARKETING_VERSION: 4.2.3
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~7266182338
          ADMOB_UNIT_ID: ca-app-pub-5587141252700968/3350341396
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~7266182338
          ADMOB_UNIT_ID: ca-app-pub-5587141252700968/3350341396
  ReactionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ReactionTests
    settings:
      base:
        INFOPLIST_FILE: ReactionTests/Info.plist
    dependencies:
      - target: ReactionLocal
  ReactionUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ReactionUITests
    settings:
      base:
        INFOPLIST_FILE: ReactionUITests/Info.plist
    dependencies:
      - target: ReactionLocal
