package handler

const (
	WithdrawSuccess                    = "Withdraw Success!"
	Healthy                            = "Healthy"
	Success                            = "Success"
	InvalidValue                       = "Invalid Value"
	AuthenticationFailure              = "Authentication Failure"
	UserSignupSuccess                  = "Sign Up Success!"
	UserSignupFailure                  = "Sign Up Failure..."
	UserUpdateSuccess                  = "User Update Success !"
	UserUpdateFailure                  = "User Update Failure..."
	CharaListFailure                   = "Get Chara List Failure..."
	InvalidRequestParameter            = "Invalid Request Parameter"
	ItemNotFound                       = "item not found"
	AlarmListFailure                   = "Get Alarm List Failure..."
	AlarmAddFailure                    = "Add Alarm Failure..."
	AlarmAddSuccess                    = "Add Alarm Success!"
	AlarmDeleteFailure                 = "Delete Alarm Failure..."
	AlarmDeleteSuccess                 = "Delete Alarm Success!"
	AlarmEditFailure                   = "Edit Alarm Failure..."
	AlarmEditSuccess                   = "Edit Alarm Success!"
	FailedToGetUserInfo                = "Failed to Get User Info"
	FailedToWithdraw                   = "Failed to withdraw"
	ErrorInvalidValue                  = "error invalid value"
	ErrorAuthenticationFailure         = "error authentication failure"
	ErrorAlarmAlreadyExists            = "error alarm already exists"
	ErrorCanNotFindEnvironmentVariable = "error can not find environment variable"
)
