name: Reaction

options:
  deploymentTarget:
    iOS: 17.0
schemes:
  Development:
    build:
      targets:
        ReactionDevelopment: all
    run:
      config: Debug
  Production:
    build:
      targets:
        ReactionProduction: all
    run:
      config: Debug
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5RH346BQ66
    MARKETING_VERSION: 5.2.1
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: 1
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.8.0
  LicenseList:
    url: https://github.com/cybozu/LicenseList
    from: 2.0.3
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.14.0

targets:
  ReactionDevelopment:
    type: application
    platform: iOS
    sources:
      - path: Reaction
      - path: Config/Development
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Development
        CODE_SIGN_ENTITLEMENTS: Config/Development/ReactionDevelopment.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.reaction.development
    info:
      path: Reaction/Info/Info-Develop.plist
      properties:
        Appearance: Light
        CFBundleDisplayName: Reaction
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchScreen:
          UIColorName: app-background-color
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeRight]
        UIRequiresFullScreen: YES
        UIAppFonts:
          - MPLUS2-VariableFont.ttf
        MinimumOSVersion: "17.0"
        REACTIONS_ENDPOINT: https://reaction-development.swiswiswift.com/resource/reaction/reactions.json
    dependencies:
      - package: Rswift
        product: RswiftLibrary
      - package: LicenseList
        product: LicenseList
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
      - plugin: PrepareLicenseList
        package: LicenseList
  ReactionProduction:
    type: application
    platform: iOS
    sources:
      - path: Reaction
      - path: Config/Production
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
        CODE_SIGN_ENTITLEMENTS: Config/Production/ReactionProduction.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        PRODUCT_BUNDLE_IDENTIFIER: com.example.junpei.chemi
    info:
      path: Reaction/Info/Info-Production.plist
      properties:
        Appearance: Light
        CFBundleDisplayName: Reaction
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchScreen:
          UIColorName: app-background-color
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeRight]
        UIRequiresFullScreen: YES
        UIAppFonts:
          - MPLUS2-VariableFont.ttf
        MinimumOSVersion: "17.0"
        REACTIONS_ENDPOINT: https://reaction-development.swiswiswift.com/resource/reaction/reactions.json
    dependencies:
      - package: Rswift
        product: RswiftLibrary
      - package: LicenseList
        product: LicenseList
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
      - plugin: PrepareLicenseList
        package: LicenseList
