name: Build Admin API Image

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::392961483375:role/reaction-github-action-role

jobs:
  build_admin_image:
    name: build admin api image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: github-action-role-${{ github.run_id }}
        aws-region: ap-northeast-1

    - name: configure aws profiles
      run: |
        mkdir ~/.aws
        cp .github/workflows/aws_config/config ~/.aws/config

    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64

    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build Admin image
      working-directory: application
      run: make build-admin-image
