name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.1.app
  MINT_PATH: .mint/lib
  MINT_LINK_PATH: .mint/bin

jobs:
  build:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # Mintのインストール
    - name: Install Mint
      run: brew install mint

    # Mintのキャッシュの取得
    - name: Cache Mint packages
      uses: actions/cache/restore@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    # Mintで管理しているライブラリのインストール
    - name: Install Mint Library
      run: mint bootstrap

    # Mintのキャッシュの保存
    - name: Cache Mint packages
      uses: actions/cache/save@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

    # Lintによるチェック
    - name: Swiftlint 
      run: mint run swiftlint swiftlint --strict

