name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app
  MINT_PATH: .mint/lib
  MINT_LINK_PATH: .mint/bin
  GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_FOR_DEVELOPMENT }}

jobs:
  build:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # Mintのインストール
    - name: Install Mint
      run: brew install mint

    # Mintのキャッシュの取得
    - name: Cache Mint packages
      uses: actions/cache/restore@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    # Mintで管理しているライブラリのインストール
    - name: Install Mint Library
      run: mint bootstrap

    # Mintのキャッシュの保存
    - name: Cache Mint packages
      uses: actions/cache/save@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

    # Lintによるチェック
    - name: Swiftlint 
      run: mint run swiftlint swiftlint --strict

    # GoogleService-Info.plistを作成
    - name: Create GoogleService-Info.plist
      run: echo $GOOGLE_SERVICE_INFO_PLIST > Config/Development/GoogleService-Info.plist

    # プロジェクト生成
    - name: Generate Project
      run: mint run xcodegen xcodegen generate

    # R.generated.swift作成（BuildToolPluginがうまく動かないため）
    - name: Generate R.generated.swift
      run: mint run R.swift rswift generate --xcodeproj Reaction.xcodeproj --target ReactionDevelopment Reaction/R.generated.swift

    # プロジェクト生成（BuildToolPluginがうまく動かないため）
    - name: Generate Project
      run: mint run xcodegen xcodegen generate

    # シミュレーター一覧
    - name: Show Simulator List
      run: xcrun simctl list

    # テスト実行
    - name: Run Tests
      run: xcodebuild test CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -project Reaction.xcodeproj -scheme "Development" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' -skipPackagePluginValidation test

