name: Test for Admin API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - application/**
    branches: 
      - main
      - develop

jobs:
  test_admin_api:
    runs-on: ubuntu-latest

    steps:
    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v4

    # Go言語のセットアップ
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.2

    # Mock環境のセットアップ
    - name: Setup Mock
      working-directory: local
      run: make setup

    # Local Stack の起動完了まで待つ
    - name: Wait SetUp Localstack
      run: sleep 30s

    # Application API の実行
    - name: Run Test
      env:
          AWS_ACCESS_KEY_ID: "dummy"
          AWS_SECRET_ACCESS_KEY: "dummy"
      working-directory: application
      run: make test
